#!/bin/sh
if [ $# -ne 2 ]
 then
  echo "this script requires 2 inputs, numbers > 0"
  exit
fi

if [ `echo $1 $2 | grep '[a-zA-Z]' | wc -l` -ne 0 ]
 then
  echo 'Error: Input requires two numbers > 0'
  exit
fi

if [ $1 -lt 0 -o $2 -lt 0 ]
 then
  echo 'Error numbers must be > 0'
  exit
fi

smallest=0
largest=0

if [ $1 -gt $2 ]
 then
  smallest=$2
  largest=$1
 else
  smallest=$1
  largest=$2
fi

echo largest is $largest
echo smallest is $smallest
